# Using functions

## Lecture objectives

1. Demonstrate how to create a function that can query an API

In the previous lecture, we experimented with the BART API. Now, let's combine all this code into a function.

If you haven't used functions before, [check out this tutorial](https://swcarpentry.github.io/python-novice-inflammation/08-func/index.html) first.

Why might we use a function?
* If we will use the same code repeatedly (e.g. requesting departures from different BART stations), a function makes our code more concise
* Functions can make the code more readable, by making it modular

Here is the code from the previous lecture that prints departures from 12th St station.

In [1]:
import requests
import json
import pandas as pd
from IPython.display import display

APIkey = 'QB8J-5LTQ-9W9T-DWEI'  # replace XXXX with the API key you used in the previous lecture
requestString = 'http://api.bart.gov/api/etd.aspx?cmd=etd&orig=12TH&json=y&key='+APIkey

r = requests.get(requestString)
d = json.loads(r.text)
etd = d['root']['station'][0]['etd']

for e in etd:
    print('\nTrains to {}'.format(e['destination']))
    display(pd.DataFrame(e['estimate']))

Trains to Antioch

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,5,3,North,8,YELLOW,#ffff33,1,64,0,0
1,20,3,North,8,YELLOW,#ffff33,1,0,0,0

Trains to Berryessa

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,5,2,South,6,ORANGE,#ff9933,1,0,0,0
1,32,2,South,6,ORANGE,#ff9933,1,0,0,0

Trains to Millbrae

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,32,2,South,8,YELLOW,#ffff33,1,0,0,0

Trains to Richmond

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,4,1,North,6,ORANGE,#ff9933,1,0,0,0
1,18,1,North,6,ORANGE,#ff9933,1,0,0,0

Trains to SFO/Millbrae

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,3,2,South,8,YELLOW,#ffff33,1,0,0,0

We can create a function by simply indenting the code, and adding a `def()` statement at the start, to define the function.

In [4]:
def getArrivalTimes():
    requestString = 'http://api.bart.gov/api/etd.aspx?cmd=etd&orig=12TH&json=y&key='+APIkey

    r = requests.get(requestString)
    d = json.loads(r.text)
    etd = d['root']['station'][0]['etd']

    for e in etd:
        print('\nTrains to {}'.format(e['destination']))
        display(pd.DataFrame(e['estimate']))

#defを使うからと言って、特別なことはない。defなし、の場合は"requestString ="という形式だったのが、
#defありだと"getArrivalTimes(): requestString = "という形になって、()の中に変数を入れられるようになる

We can now call this function any time we want to get the latest arrival times.

In [3]:
getArrivalTimes()

Trains to Antioch

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,4,3,North,8,YELLOW,#ffff33,1,77,0,0
1,19,3,North,8,YELLOW,#ffff33,1,0,0,0

Trains to Berryessa

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,5,2,South,6,ORANGE,#ff9933,1,0,0,0
1,31,2,South,6,ORANGE,#ff9933,1,0,0,0

Trains to Millbrae

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,31,2,South,8,YELLOW,#ffff33,1,0,0,0

Trains to Richmond

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,3,1,North,6,ORANGE,#ff9933,1,0,0,0
1,18,1,North,6,ORANGE,#ff9933,1,0,0,0

Trains to SFO/Millbrae

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,2,2,South,8,YELLOW,#ffff33,1,0,0,0

The advantages of creating a function will become much more clear if we generalize.

Our function above only returns departure times for 12th St station. What if we want to tell the function the station we are interested in? To do this, we need to add an *argument*. This argument creates a variable that is internal to the function (i.e., it disappears once the function terminates).

Let's call this argument `station`. We then insert the station into the string that we pass to the API, `requestString`. Note the use of `.format()` to put the station and API key into the string.

In [5]:
def getArrivalTimes(station):
    requestString = 'http://api.bart.gov/api/etd.aspx?cmd=etd&orig={}&json=y&key={}'.format(station, APIkey)
    
    r = requests.get(requestString)
    d = json.loads(r.text)
    etd = d['root']['station'][0]['etd']

    for e in etd:
        print('\nTrains to {}'.format(e['destination']))
        display(pd.DataFrame(e['estimate']))

getArrivalTimes('12TH')

#最初の2段に入っているstationはetdの中に入っている'station'とは関係ない、ことに留意を
#getArrivalTimes(station)のstationは、別に何だっていい。yでもaでも何でもいい。2段目のstationと一致していさえすればいい
#最後の行のgetArrivalTimes('12TH')にあるように、stationのところに何が入るか、がここで指定され、それによって結果が変わる

Trains to Antioch

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,12,3,North,8,YELLOW,#ffff33,1,104,0,0

Trains to Berryessa

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,23,2,South,6,ORANGE,#ff9933,1,0,0,0

Trains to Millbrae

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,23,2,South,8,YELLOW,#ffff33,1,0,0,0

Trains to Richmond

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,9,1,North,6,ORANGE,#ff9933,1,0,0,0

We can get a list of stations using the `stns` command, according to the [documentation](https://api.bart.gov/docs/stn/stns.aspx).

Then let's try another station using our handy function.

In [7]:
requestString = 'http://api.bart.gov/api/stn.aspx?cmd=stns&key={}&json=y'.format(APIkey)
r = requests.get(requestString)
r.text

#ここまではcmd=etdだったのがcmd=stnsに変わっている。
#つまり、ここでは時刻表ではなく、駅のリストを出そうとしている

'{"?xml":{"@version":"1.0","@encoding":"utf-8"},"root":{"uri":{"#cdata-section":"http://api.bart.gov/api/stn.aspx?cmd=stns&json=y"},"stations":{"station":[{"name":"12th St. Oakland City Center","abbr":"12TH","gtfs_latitude":"37.803768","gtfs_longitude":"-122.271450","address":"1245 Broadway","city":"Oakland","county":"alameda","state":"CA","zipcode":"94612"},{"name":"16th St. Mission","abbr":"16TH","gtfs_latitude":"37.765062","gtfs_longitude":"-122.419694","address":"2000 Mission Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94110"},{"name":"19th St. Oakland","abbr":"19TH","gtfs_latitude":"37.808350","gtfs_longitude":"-122.268602","address":"1900 Broadway","city":"Oakland","county":"alameda","state":"CA","zipcode":"94612"},{"name":"24th St. Mission","abbr":"24TH","gtfs_latitude":"37.752470","gtfs_longitude":"-122.418143","address":"2800 Mission Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94110"},{"name":"Antioch","abbr":"ANTC","gtfs_latitude":"37.995388","gtfs_longitude":"-121.780420","address":"1600 Slatten Ranch Road","city":"Antioch","county":"Contra Costa","state":"CA","zipcode":"94509"},{"name":"Ashby","abbr":"ASHB","gtfs_latitude":"37.852803","gtfs_longitude":"-122.270062","address":"3100 Adeline Street","city":"Berkeley","county":"alameda","state":"CA","zipcode":"94703"},{"name":"Balboa Park","abbr":"BALB","gtfs_latitude":"37.721585","gtfs_longitude":"-122.447506","address":"401 Geneva Avenue","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94112"},{"name":"Bay Fair","abbr":"BAYF","gtfs_latitude":"37.696924","gtfs_longitude":"-122.126514","address":"15242 Hesperian Blvd.","city":"San Leandro","county":"alameda","state":"CA","zipcode":"94578"},{"name":"Berryessa/North San Jose","abbr":"BERY","gtfs_latitude":"37.368473","gtfs_longitude":"-121.874681","address":"1620 Berryessa Road","city":"San Jose","county":"Santa Clara","state":"CA","zipcode":"95133"},{"name":"Castro Valley","abbr":"CAST","gtfs_latitude":"37.690746","gtfs_longitude":"-122.075602","address":"3301 Norbridge Dr.","city":"Castro Valley","county":"alameda","state":"CA","zipcode":"94546"},{"name":"Civic Center/UN Plaza","abbr":"CIVC","gtfs_latitude":"37.779732","gtfs_longitude":"-122.414123","address":"1150 Market Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94102"},{"name":"Coliseum","abbr":"COLS","gtfs_latitude":"37.753661","gtfs_longitude":"-122.196869","address":"7200 San Leandro St.","city":"Oakland","county":"alameda","state":"CA","zipcode":"94621"},{"name":"Colma","abbr":"COLM","gtfs_latitude":"37.684638","gtfs_longitude":"-122.466233","address":"365 D Street","city":"Colma","county":"sanmateo","state":"CA","zipcode":"94014"},{"name":"Concord","abbr":"CONC","gtfs_latitude":"37.973737","gtfs_longitude":"-122.029095","address":"1451 Oakland Avenue","city":"Concord","county":"contracosta","state":"CA","zipcode":"94520"},{"name":"Daly City","abbr":"DALY","gtfs_latitude":"37.706121","gtfs_longitude":"-122.469081","address":"500 John Daly Blvd.","city":"Daly City","county":"sanmateo","state":"CA","zipcode":"94014"},{"name":"Downtown Berkeley","abbr":"DBRK","gtfs_latitude":"37.870104","gtfs_longitude":"-122.268133","address":"2160 Shattuck Avenue","city":"Berkeley","county":"alameda","state":"CA","zipcode":"94704"},{"name":"Dublin/Pleasanton","abbr":"DUBL","gtfs_latitude":"37.701687","gtfs_longitude":"-121.899179","address":"5801 Owens Dr.","city":"Pleasanton","county":"alameda","state":"CA","zipcode":"94588"},{"name":"El Cerrito del Norte","abbr":"DELN","gtfs_latitude":"37.925086","gtfs_longitude":"-122.316794","address":"6400 Cutting Blvd.","city":"El Cerrito","county":"contracosta","state":"CA","zipcode":"94530"},{"name":"El Cerrito Plaza","abbr":"PLZA","gtfs_latitude":"37.902632","gtfs_longitude":"-122.298904","address":"6699 Fairmount Avenue","city":"El Cerrito","county":"contracosta","state":"CA","zipcode":"94530"},{"name":"Embarcadero","abbr":"EMBR","gtfs_latitude":"37.792874","gtfs_longitude":"-122.397020","address":"298 Market Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94111"},{"name":"Fremont","abbr":"FRMT","gtfs_latitude":"37.557465","gtfs_longitude":"-121.976608","address":"2000 BART Way","city":"Fremont","county":"alameda","state":"CA","zipcode":"94536"},{"name":"Fruitvale","abbr":"FTVL","gtfs_latitude":"37.774836","gtfs_longitude":"-122.224175","address":"3401 East 12th Street","city":"Oakland","county":"alameda","state":"CA","zipcode":"94601"},{"name":"Glen Park","abbr":"GLEN","gtfs_latitude":"37.733064","gtfs_longitude":"-122.433817","address":"2901 Diamond Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94131"},{"name":"Hayward","abbr":"HAYW","gtfs_latitude":"37.669723","gtfs_longitude":"-122.087018","address":"699 \'B\' Street","city":"Hayward","county":"alameda","state":"CA","zipcode":"94541"},{"name":"Lafayette","abbr":"LAFY","gtfs_latitude":"37.893176","gtfs_longitude":"-122.124630","address":"3601 Deer Hill Road","city":"Lafayette","county":"contracosta","state":"CA","zipcode":"94549"},{"name":"Lake Merritt","abbr":"LAKE","gtfs_latitude":"37.797027","gtfs_longitude":"-122.265180","address":"800 Madison Street","city":"Oakland","county":"alameda","state":"CA","zipcode":"94607"},{"name":"MacArthur","abbr":"MCAR","gtfs_latitude":"37.829065","gtfs_longitude":"-122.267040","address":"555 40th Street","city":"Oakland","county":"alameda","state":"CA","zipcode":"94609"},{"name":"Millbrae","abbr":"MLBR","gtfs_latitude":"37.600271","gtfs_longitude":"-122.386702","address":"200 North Rollins Road","city":"Millbrae","county":"sanmateo","state":"CA","zipcode":"94030"},{"name":"Milpitas","abbr":"MLPT","gtfs_latitude":"37.410277","gtfs_longitude":"-121.891081","address":"1755 S. Milpitas Blvd.","city":"Milpitas","county":"Santa Clara","state":"CA","zipcode":"95035"},{"name":"Montgomery St.","abbr":"MONT","gtfs_latitude":"37.789405","gtfs_longitude":"-122.401066","address":"598 Market Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94104"},{"name":"North Berkeley","abbr":"NBRK","gtfs_latitude":"37.873967","gtfs_longitude":"-122.283440","address":"1750 Sacramento Street","city":"Berkeley","county":"alameda","state":"CA","zipcode":"94702"},{"name":"North Concord/Martinez","abbr":"NCON","gtfs_latitude":"38.003193","gtfs_longitude":"-122.024653","address":"3700 Port Chicago Highway","city":"Concord","county":"contracosta","state":"CA","zipcode":"94520"},{"name":"Oakland International Airport","abbr":"OAKL","gtfs_latitude":"37.713238","gtfs_longitude":"-122.212191","address":"4 Airport Drive","city":"Oakland","county":"alameda","state":"CA","zipcode":"94621"},{"name":"Orinda","abbr":"ORIN","gtfs_latitude":"37.878361","gtfs_longitude":"-122.183791","address":"11 Camino Pablo","city":"Orinda","county":"contracosta","state":"CA","zipcode":"94563"},{"name":"Pittsburg/Bay Point","abbr":"PITT","gtfs_latitude":"38.018914","gtfs_longitude":"-121.945154","address":"1700 West Leland Road","city":"Pittsburg","county":"contracosta","state":"CA","zipcode":"94565"},{"name":"Pittsburg Center","abbr":"PCTR","gtfs_latitude":"38.016941","gtfs_longitude":"-121.889457","address":"2099 Railroad Avenue","city":"Pittsburg","county":"Contra Costa","state":"CA","zipcode":"94565"},{"name":"Pleasant Hill/Contra Costa Centre","abbr":"PHIL","gtfs_latitude":"37.928468","gtfs_longitude":"-122.056012","address":"1365 Treat Blvd.","city":"Walnut Creek","county":"contracosta","state":"CA","zipcode":"94597"},{"name":"Powell St.","abbr":"POWL","gtfs_latitude":"37.784471","gtfs_longitude":"-122.407974","address":"899 Market Street","city":"San Francisco","county":"sanfrancisco","state":"CA","zipcode":"94102"},{"name":"Richmond","abbr":"RICH","gtfs_latitude":"37.936853","gtfs_longitude":"-122.353099","address":"1700 Nevin Avenue","city":"Richmond","county":"contracosta","state":"CA","zipcode":"94801"},{"name":"Rockridge","abbr":"ROCK","gtfs_latitude":"37.844702","gtfs_longitude":"-122.251371","address":"5660 College Avenue","city":"Oakland","county":"alameda","state":"CA","zipcode":"94618"},{"name":"San Bruno","abbr":"SBRN","gtfs_latitude":"37.637761","gtfs_longitude":"-122.416287","address":"1151 Huntington Avenue","city":"San Bruno","county":"sanmateo","state":"CA","zipcode":"94066"},{"name":"San Francisco International Airport","abbr":"SFIA","gtfs_latitude":"37.615966","gtfs_longitude":"-122.392409","address":"International Terminal, Level 3","city":"San Francisco Int\'l Airport","county":"sanmateo","state":"CA","zipcode":"94128"},{"name":"San Leandro","abbr":"SANL","gtfs_latitude":"37.721947","gtfs_longitude":"-122.160844","address":"1401 San Leandro Blvd.","city":"San Leandro","county":"alameda","state":"CA","zipcode":"94577"},{"name":"South Hayward","abbr":"SHAY","gtfs_latitude":"37.634375","gtfs_longitude":"-122.057189","address":"28601 Dixon Street","city":"Hayward","county":"alameda","state":"CA","zipcode":"94544"},{"name":"South San Francisco","abbr":"SSAN","gtfs_latitude":"37.664245","gtfs_longitude":"-122.443960","address":"1333 Mission Road","city":"South San Francisco","county":"sanmateo","state":"CA","zipcode":"94080"},{"name":"Union City","abbr":"UCTY","gtfs_latitude":"37.590630","gtfs_longitude":"-122.017388","address":"10 Union Square","city":"Union City","county":"alameda","state":"CA","zipcode":"94587"},{"name":"Walnut Creek","abbr":"WCRK","gtfs_latitude":"37.905522","gtfs_longitude":"-122.067527","address":"200 Ygnacio Valley Road","city":"Walnut Creek","county":"contracosta","state":"CA","zipcode":"94596"},{"name":"Warm Springs/South Fremont","abbr":"WARM","gtfs_latitude":"37.502171","gtfs_longitude":"-121.939313","address":"45193 Warm Springs Blvd","city":"Fremont","county":"alameda","state":"CA","zipcode":"94539"},{"name":"West Dublin/Pleasanton","abbr":"WDUB","gtfs_latitude":"37.699756","gtfs_longitude":"-121.928240","address":"6501 Golden Gate Drive","city":"Dublin","county":"alameda","state":"CA","zipcode":"94568"},{"name":"West Oakland","abbr":"WOAK","gtfs_latitude":"37.804872","gtfs_longitude":"-122.295140","address":"1451 7th Street","city":"Oakland","county":"alameda","state":"CA","zipcode":"94607"}]},"message":""}}'

In [9]:
getArrivalTimes('WARM')
#これは先に"def getArrivalTimes(): requestString ="というので定義しているgetArrivalTimes()を使っている

Trains to Berryessa

,minutes,platform,direction,length,color,hexcolor,bikeflag,delay,cancelflag,dynamicflag
0,15,1,South,6,ORANGE,#ff9933,1,0,0,0
1,35,1,South,6,ORANGE,#ff9933,1,0,0,0
2,62,1,South,6,ORANGE,#ff9933,1,0,0,0

So far, our function only prints the output. We might want it to return the dataframe rather than (or as well as) printing it.

Let's do this by creating a list of dataframes. For each one, we want to add the destination (since this isn't a column in the output). Then, we can use `pd.concat()` to concatenate into a single dataframe.

In [11]:
def getArrivalTimes(station):
    requestString = 'http://api.bart.gov/api/etd.aspx?cmd=etd&orig={}&json=y&key={}'.format(station, APIkey)

    r = requests.get(requestString)
    d = json.loads(r.text)
    etd = d['root']['station'][0]['etd']
#ここまでは上にすでにあった内容で、いかが新たなもの
#Pythonにおける DataFrame（データフレーム） とは、表（テーブル）形式のデータを扱うための構造で、
#主に Pandasライブラリ によって提供されている
#Excelのシートのようなものとイメージすると分かりやすい
#DataFrame(Pandas)以外の形式としては、listやdictがある
#"df = pd.DataFrame()"というfunctionを使う事で、listやdictをdataframeに変える事ができる
#"pd.concat()"は複数の表をまとめるfunction
#"df_list"は複数の行き先のデータを一時保存するリスト

    df_list = [] #各行き先の情報を DataFrame に変換して格納するためのリスト（この時点ではカラ）
    for e in etd:
        # create the dataframe
        df = pd.DataFrame(e['estimate']) #この段階では、dataframeには行き先情報が入っていない
        # add the column with the destination
        df['destination'] = e['destination'] #ここでは新たなdataframeを作っているのではなく、"destination"の列を追加しているだけ
        # add it to the end of the list
        df_list += [df] # df_list.append(df) would also have worked
#この最後の行で、df を df_list にどんどん追加していっている。
#".append()"というfunctionは、()の中身を.の前の関数に追加していくもの（なのでdf_list.append(df)と同じ、と言っている）
#例えば、
#a = []  # 空のリスト
#a.append(10)  # → [10]
#a.append(20)  # → [10, 20]
    
    # now the loop has finished, return the concatenated dataframes
    bigDf = pd.concat(df_list) #concatは表を縦に結合して、ひとつの大きな表にまとめるもの
    return bigDf

getArrivalTimes('12TH')

KeyError: 'etd'

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> Adapt the function to add a column with the origin station too.
</div>

<div class="alert alert-block alert-info">
<h3>Key Takeaways</h3>
<ul>
  <li>Functions are simple to create, and help to organize your code in a logical way.</li>
</ul>
</div>