## Module 10 Class activities
This notebook is a starting point for the exercises and activities that we'll do in class. 

We'll revisit our analysis of ADUs, and try and speed things up and reduce memory usage.

Then, we'll have some practice with SQL.

Before you attempt any of these activities, make sure to watch the video lectures for this module.

### Optimizing data types and parsing csv files
Let's revist the ADU data that we saw in Lecture 12 (classification). There are two csv files that we read in – one with the permit data, and one with the parcel data.

In [10]:
import pandas as pd
permits = pd.read_csv('../lectures/data/ADUs/ADU_permits.csv')  # this file should be in your GitHub folder
permits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26488 entries, 0 to 26487
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Assessor Book                  26488 non-null  float64
 1   Assessor Page                  26488 non-null  float64
 2   Assessor Parcel                26488 non-null  object
 3   # of Accessory Dwelling Units  26488 non-null  float64
dtypes: float64(3), object(1)
memory usage: 827.9+ KB

In [3]:
permits

,Assessor Book,Assessor Page,Assessor Parcel,# of Accessory Dwelling Units
0,2126.0,24.0,041,1.0
1,2245.0,10.0,006,1.0
2,2640.0,7.0,014,1.0
3,2671.0,22.0,024,1.0
4,2301.0,9.0,003,1.0
...,...,...,...,...
26483,2325.0,20.0,015,1.0
26484,5477.0,16.0,003,1.0
26485,2639.0,3.0,018,1.0
26486,2231.0,18.0,015,1.0
26487,5115.0,4.0,014,1.0

In [2]:
parcels = pd.read_csv('../lectures/data/ADUs/parcels.csv')
parcels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790807 entries, 0 to 790806
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   APN                790807 non-null  object
 1   UseType            790758 non-null  object
 2   UseDescription     790758 non-null  object
 3   YearBuilt1         780083 non-null  float64
 4   Units1             780083 non-null  float64
 5   Bedrooms1          780083 non-null  float64
 6   Bathrooms1         780083 non-null  float64
 7   SQFTmain1          780083 non-null  float64
 8   Roll_LandValue     784705 non-null  float64
 9   Roll_ImpValue      784705 non-null  float64
 10  Roll_LandBaseYear  790807 non-null  int64
 11  Roll_ImpBaseYear   790807 non-null  int64
 12  CENTER_LAT         790807 non-null  float64
 13  CENTER_LON         790807 non-null  float64
dtypes: float64(9), int64(2), object(3)
memory usage: 84.5+ MB

In [13]:
parcels
# there seems no data with below decimal points

,APN,UseType,UseDescription,YearBuilt1,Units1,Bedrooms1,Bathrooms1,SQFTmain1,Roll_LandValue,Roll_ImpValue,Roll_LandBaseYear,Roll_ImpBaseYear,CENTER_LAT,CENTER_LON
0,8543-009-073,Residential,Single,1940.0,1.0,3.0,2.0,1174.0,111510.0,112960.0,2000,2000,34.093940,-117.968917
1,8028-013-011,Residential,Two Units,1901.0,1.0,2.0,1.0,1115.0,117403.0,189350.0,1988,1988,33.921639,-118.043151
2,7563-037-055,Residential,Single,1962.0,1.0,4.0,2.0,2153.0,45925.0,89381.0,1975,1975,33.720274,-118.325022
3,7563-037-054,Residential,Single,1959.0,1.0,3.0,2.0,1862.0,676304.0,169069.0,2008,2008,33.720115,-118.325069
4,7563-037-053,Residential,Single,1965.0,1.0,3.0,2.0,2206.0,762619.0,190654.0,2020,2020,33.719947,-118.325116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790802,2004-001-009,Residential,Single,1978.0,1.0,4.0,3.0,2226.0,134500.0,201858.0,1984,1984,34.220323,-118.623050
790803,2004-001-008,Residential,Single,1978.0,1.0,4.0,3.0,2423.0,123435.0,213347.0,1980,1980,34.220334,-118.622706
790804,2004-001-005,Residential,Single,1973.0,1.0,4.0,2.0,2057.0,505922.0,190867.0,2018,2018,34.219858,-118.620676
790805,2004-001-004,Residential,Single,1973.0,1.0,5.0,3.0,2479.0,356150.0,245944.0,2010,2010,34.220039,-118.620668
790806,2004-001-003,Residential,Single,1973.0,1.0,4.0,3.0,2090.0,684054.0,289482.0,2006,2006,34.220220,-118.620669

For me, the permits data takes 492KB of memory. The parcels data uses 84MB. Imagine that you had a much bigger data file (perhaps more counties, or perhaps more columns). How can you reduce the memory requirements of these dataframes?

*Hint*: I didn't mention this in the lecture, but pandas has a new "nullable integer" datatype which can take missing values (NaNs).

To take advantage of this, use `Int16`, `Int32`, etc. rather than `int16`, `int32`, etc. The capital I is the nullable integer datatype; the lower-case i is the numpy datatype. [See here for a detailed explanation.](https://pandas.pydata.org/docs/user_guide/integer_na.html)

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> Reduce the memory usage of each dataframe as much as you can.
</div>

In [11]:
permits.drop(columns=['Assessor Parcel']).max().max()

7563.0

In [12]:
# your code here
for col in permits.columns:
    if permits[col].dtype != 'object': # skip the string column (srprec)
        permits[col] = permits[col].astype('int16')
permits.info()
permits.drop(columns=['Assessor Parcel']).max().max()

#I lost data when I used 'int8'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26488 entries, 0 to 26487
Data columns (total 4 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Assessor Book                  26488 non-null  int16
 1   Assessor Page                  26488 non-null  int16
 2   Assessor Parcel                26488 non-null  object
 3   # of Accessory Dwelling Units  26488 non-null  int16
dtypes: int16(3), object(1)
memory usage: 362.3+ KB

7563

In [17]:
parcels.drop(columns=['APN', 'UseType', 'UseDescription']).max().max()

913370140.0

In [26]:
for col in parcels.columns:
    if parcels[col].dtype != 'object' and col not in ['CENTER_LAT', 'CENTER_LON']:
        parcels[col] = parcels[col].astype('Int32')
parcels.info()
parcels.drop(columns=['APN', 'UseType', 'UseDescription']).max().max()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790807 entries, 0 to 790806
Data columns (total 14 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   APN                790807 non-null  object
 1   UseType            790758 non-null  object
 2   UseDescription     790758 non-null  object
 3   YearBuilt1         780083 non-null  Int32
 4   Units1             780083 non-null  Int32
 5   Bedrooms1          780083 non-null  Int32
 6   Bathrooms1         780083 non-null  Int32
 7   SQFTmain1          780083 non-null  Int32
 8   Roll_LandValue     784705 non-null  Int32
 9   Roll_ImpValue      784705 non-null  Int32
 10  Roll_LandBaseYear  790807 non-null  Int32
 11  Roll_ImpBaseYear   790807 non-null  Int32
 12  CENTER_LAT         790807 non-null  float64
 13  CENTER_LON         790807 non-null  float64
dtypes: Int32(9), float64(2), object(3)
memory usage: 64.1+ MB

913370140.0

Now, imagine that the dataframes wouldn't even load into memory in the first place?

Also imagine that you don't need the `Bathrooms1` column.

Use additional arguments to `pd.read_csv()` and the datatypes you used in the answer above to load in the dataframes again.

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> Load the dataframes from disk in the most memory-efficient way possible.
</div>

In [28]:
parcels.columns

Index(['APN', 'UseType', 'UseDescription', 'YearBuilt1', 'Units1', 'Bedrooms1',
       'Bathrooms1', 'SQFTmain1', 'Roll_LandValue', 'Roll_ImpValue',
       'Roll_LandBaseYear', 'Roll_ImpBaseYear', 'CENTER_LAT', 'CENTER_LON'],
      dtype='object')

In [ ]:
# your code here
parcels_selected = pd.read_csv('../lectures/data/ADUs/parcels.csv'), 
                 usecols=['APN', 'UseType', 'UseDescription', 'YearBuilt1', ''],
                 dtype={'srprec':'str', 'PR_14_N':'int32'})
parcels_selected.info()

### Speeding up joins

Now let's try and join them together in an efficient way.

Remember `%timeit` (for a line of code) and `%%timeit` (for a cell) will tell you how long your code takes to run.

Before we join, we need to drop the rows with no parcel number, and create a concatenated column for the APN.

In [33]:
permits = permits[permits['Assessor Parcel']!='***']
permits['APN'] = (permits['Assessor Book'].astype(int).astype(str).str.zfill(4) + '-' 
                   + permits['Assessor Page'].astype(int).astype(str).str.zfill(3) + '-'
                   + permits['Assessor Parcel'].astype(int).astype(str).str.zfill(3))
#drop the duplicates (take the first)
permits = permits.groupby('APN').first()
parcels = parcels.groupby('APN').first()

permits.head()

,Assessor Book,Assessor Page,Assessor Parcel,# of Accessory Dwelling Units
APN,,,,
2004-004-010,2004,4,010,1
2004-004-011,2004,4,011,1
2004-004-013,2004,4,013,1
2004-004-019,2004,4,019,1
2004-006-001,2004,6,001,1

This is how we joined the parcels in lecture.

In [34]:
joinedDf = parcels.join(permits, how='left') # left is the default so we could omit that argument

How long does that take?

In [31]:
%timeit joinedDf = parcels.join(permits, how='left')

78.9 ms ± 5.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

What if we use `pd.merge()` on a column, rather than the index? 

Let's first reset the indexes, so that `APN` becomes a regular column.

In [32]:
parcels.reset_index(inplace=True)
permits.reset_index(inplace=True)

<div class="alert alert-block alert-info">
<strong>Exercise:</strong> How long does it take to merge using the columns?</div>

In [ ]:
# your code here

# joinとmergeを比べるとmergeの方が時間がかかる。小さいデータなら問題無いが、大きなデータになると差が出てくる

If you are curious, indexes are faster because they are [stored as hashes](https://stackoverflow.com/questions/27238066/what-is-the-point-of-indexing-in-pandas).

Before we move on, let's create the `has_adu` column as we did before.

In [46]:
joinedDf['has_adu'] = joinedDf['# of Accessory Dwelling Units']>=1

In [50]:
joinedDf

,UseType,UseDescription,YearBuilt1,Units1,Bedrooms1,Bathrooms1,SQFTmain1,Roll_LandValue,Roll_ImpValue,Roll_LandBaseYear,Roll_ImpBaseYear,CENTER_LAT,CENTER_LON,Assessor Book,Assessor Page,Assessor Parcel,# of Accessory Dwelling Units,has_adu
APN,,,,,,,,,,,,,,,,,,
2004-001-003,Residential,Single,1973,1,4,3,2090,684054,289482,2006,2006,34.220220,-118.620669,NaN,NaN,NaN,NaN,False
2004-001-004,Residential,Single,1973,1,5,3,2479,356150,245944,2010,2010,34.220039,-118.620668,NaN,NaN,NaN,NaN,False
2004-001-005,Residential,Single,1973,1,4,2,2057,505922,190867,2018,2018,34.219858,-118.620676,NaN,NaN,NaN,NaN,False
2004-001-008,Residential,Single,1978,1,4,3,2423,123435,213347,1980,1980,34.220334,-118.622706,NaN,NaN,NaN,NaN,False
2004-001-009,Residential,Single,1978,1,4,3,2226,134500,201858,1984,1984,34.220323,-118.623050,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563-037-053,Residential,Single,1965,1,3,2,2206,762619,190654,2020,2020,33.719947,-118.325116,NaN,NaN,NaN,NaN,False
7563-037-054,Residential,Single,1959,1,3,2,1862,676304,169069,2008,2008,33.720115,-118.325069,NaN,NaN,NaN,NaN,False
7563-037-055,Residential,Single,1962,1,4,2,2153,45925,89381,1975,1975,33.720274,-118.325022,NaN,NaN,NaN,NaN,False
8028-013-011,Residential,Two Units,1901,1,2,1,1115,117403,189350,1988,1988,33.921639,-118.043151,NaN,NaN,NaN,NaN,False
8543-009-073,Residential,Single,1940,1,3,2,1174,111510,112960,2000,2000,34.093940,-117.968917,NaN,NaN,NaN,NaN,False

## SQL

Finally, let's do some simple SQL queries on the joined dataframe.

Implement the following queries as SQL, using `pandasql`.

1. What's the total land value of all the parcels? (The column `Roll_LandValue`.)

2. How many parcels have ADUs? 

3. What's the average area of the building size (`SQFTmain1`), with and without an ADU? (Hint: use `GROUP BY`.)

4. Same as above, but for residential parcels only (`UseType='Residential'`)

Compare your results to a typical `pandas` query.

In [45]:
from pandasql import PandaSQL
pdsql = PandaSQL()

# your code here

pdsql('SELECT SUM(Roll_LandValue) FROM joinedDf;')

   SUM(Roll_LandValue)
0         406395931523

In [48]:
pdsql('SELECT COUNT(*) FROM joinedDf WHERE has_adu=TRUE;')

   COUNT(*)
0     25161

In [54]:
pdsql('SELECT AVG(SQFTmain1) FROM joinedDf GROUP BY has_adu;')

   AVG(SQFTmain1)
0     3089.019249
1     2244.086022

<div class="alert alert-block alert-info">
<h3>You should now be able to:</h3>
<ul>
  <li>Deal with larger datasets on a standard laptop computer</li>
  <li>Profile your code to identify bottlenecks</li>
  <li>Write simple SQL queries</li>
  <li>Go forth and do data science!</li>
</ul>
</div>